name: 'AI-based PR Reviewer & Summarizer with Chat Capabilities'
description: 'AI-based PR Reviewer & Summarizer with Chat Capabilities'
inputs:
  debug:
    required: false
    description: 'Enable debug mode'
    default: 'false'
  disable_review:
    required: false
    description: 'Only provide the summary and skip the code review.'
    default: 'false'
  disable_release_notes:
    required: false
    description: 'Disable release notes'
    default: 'false'
  max_files:
    required: false
    description:
      'Max files to summarize and review. Less than or equal to 0 means no
      limit.'
    default: '150'
  review_simple_changes:
    required: false
    description: 'Review even when the changes are simple'
    default: 'false'
  review_comment_lgtm:
    required: false
    description: 'Leave comments even if the patch is LGTM'
    default: 'false'
  path_filters:
    required: false
    description: |
      The path filters, e.g., "src/**.py", "!dist/**", each line will be considered as one pattern.
      See also

      - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
      - https://github.com/isaacs/minimatch
    default: |
      !dist/**
      !**/*.app
      !**/*.bin
      !**/*.bz2
      !**/*.class
      !**/*.db
      !**/*.csv
      !**/*.tsv
      !**/*.dat
      !**/*.dll
      !**/*.dylib
      !**/*.egg
      !**/*.glif
      !**/*.gz
      !**/*.xz
      !**/*.zip
      !**/*.7z
      !**/*.rar
      !**/*.zst
      !**/*.ico
      !**/*.jar
      !**/*.tar
      !**/*.war
      !**/*.lo
      !**/*.log
      !**/*.mp3
      !**/*.wav
      !**/*.wma
      !**/*.mp4
      !**/*.avi
      !**/*.mkv
      !**/*.wmv
      !**/*.m4a
      !**/*.m4v
      !**/*.3gp
      !**/*.3g2
      !**/*.rm
      !**/*.mov
      !**/*.flv
      !**/*.iso
      !**/*.swf
      !**/*.flac
      !**/*.nar
      !**/*.o
      !**/*.ogg
      !**/*.otf
      !**/*.p
      !**/*.pdf
      !**/*.doc
      !**/*.docx
      !**/*.xls
      !**/*.xlsx
      !**/*.ppt
      !**/*.pptx
      !**/*.pkl
      !**/*.pickle
      !**/*.pyc
      !**/*.pyd
      !**/*.pyo
      !**/*.pub
      !**/*.pem
      !**/*.rkt
      !**/*.so
      !**/*.ss
      !**/*.eot
      !**/*.exe
      !**/*.pb.go
      !**/*.lock
      !**/*.ttf
      !**/*.yaml
      !**/*.yml
      !**/*.cfg
      !**/*.toml
      !**/*.ini
      !**/*.mod
      !**/*.sum
      !**/*.work
      !**/*.json
      !**/*.mmd
      !**/*.svg
      !**/*.jpeg
      !**/*.jpg
      !**/*.png
      !**/*.gif
      !**/*.bmp
      !**/*.tiff
      !**/*.webm
      !**/*.woff
      !**/*.woff2
      !**/*.dot
      !**/*.md5sum
      !**/*.wasm
      !**/*.snap
      !**/*.parquet
      !**/gen/**
      !**/_gen/**
      !**/generated/**
      !**/@generated/**
      !**/vendor/**
      !**/*.min.js
      !**/*.min.js.map
      !**/*.min.js.css
      !**/*.tfstate
      !**/*.tfstate.backup
  system_message:
    required: false
    description: 'System message to be sent to Erag'
    default: |
      You are `Erag Reviewer` (aka `github-actions[bot]`).
      Your purpose is to act as a highly experienced 
      software engineer and provide a thorough review of the code hunks
      and suggest code snippets to improve key areas such as:
        - Logic
        - Security
        - Performance
        - Data races
        - Consistency
        - Error handling
        - Maintainability
        - Modularity
        - Complexity
        - Optimization
        - Best practices: DRY, SOLID, KISS

      Do not comment on minor code style issues, missing 
      comments/documentation. Identify and resolve significant 
      concerns to improve overall code quality while deliberately 
      disregarding minor issues.
  model:
    required: false
    description:
      'Model to use for review.'
    default: 'gpt-4o'
  erag_retries:
    required: false
    description:
      'How many times to retry Erag API in case of timeouts or errors?'
    default: '3'
  erag_concurrency_limit:
    required: false
    description: 'How many concurrent API calls to make to Erag servers?'
    default: '6'
  github_concurrency_limit:
    required: false
    description: 'How many concurrent API calls to make to GitHub?'
    default: '6'
  erag_base_url:
    required: false
    description: 'The url of the erag api interface.'
    default: 'https://erag.trilogy.com/api/v2'
  erag_project_name:
    required: false
    description: 'The project name to use when querying erag.'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
